real_estate_data_platform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES__HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES__PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES__USER', 'etl_user') }}"
      password: "{{ env_var('POSTGRES__PASSWORD', 'etl_pass') }}"
      dbname: "{{ env_var('POSTGRES__DB', 'etl_db') }}"
      schema: gold
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('POSTGRES__HOST', 'localhost') }}"
      port: "{{ env_var('POSTGRES__PORT', '5432') | int }}"
      user: "{{ env_var('POSTGRES__USER', 'etl_user') }}"
      password: "{{ env_var('POSTGRES__PASSWORD', 'etl_pass') }}"
      dbname: "{{ env_var('POSTGRES__DB', 'etl_db') }}"
      schema: gold
      threads: 8
